# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41b62ac5e26eac9ded6ea4254b808719f8f45b149ee109cfd0477c408e630370b27ffa87fcb4f5e7d8d51d9332436ba9486d72454fd43dadb787fe57b5dc9dd3

test:
  secret_key_base: 74675bbd2fa6fb1324f4a46f5168a357bb76a4a5a480838e8ddccb7feba1ee7b1cfa98c06fc7c26590d016b1df8736ac5b41f8dc53f1bb04cc021d609d44412b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
